version: "3.7"

services:
  laravel:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "polimundo"
    volumes:
      - persistent_mysql:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pmysql" ]
      retries: 3
      timeout: 5s

networks:
  laravel:
    driver: bridge

volumes:
  persistent_mysql:
