#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
chown -R nobody:nobody /var/www/html/storage

/usr/local/bin/composer install --no-interaction --no-ansi --no-progress

/usr/local/bin/php -r "file_exists('.env') || copy('.env.example', '.env');"

/usr/local/bin/php artisan key:generate --ansi

/usr/bin/supervisord -c /etc/supervisor.d/supervisord.ini
